version: "3.5"
services:
  php_fpm:
      build: .
      container_name: php_fpm
      working_dir: /usr/share/nginx/app
      networks:
        - app
      volumes:
          - ./:/usr/share/nginx/app
  nginx:
      image: nginx:1.15
      container_name: nginx
      working_dir: /usr/share/nginx/app
      networks:
        - app
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/app
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: app_mysql
      networks:
        - app
      environment:
        - MYSQL_DATABASE = ${DB_DATABASE}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
networks:
  app:
    driver: bridge
